Repository OCA/l10n-france, pull requests merged in 2021-08, with the labels that each got.

#298 [REF][14.0] Fix CI pre-commit + travis.yml, ignoring modules
  .pre-commit-config.yaml
  .travis.yml
  account_balance_ebp_csv_export/__manifest__.py
  account_banking_fr_lcr/__manifest__.py
  account_statement_import_fr_cfonb/__manifest__.py
  l10n_fr_account_invoice_import_facturx/__manifest__.py
  l10n_fr_account_tax_unece/__manifest__.py
  l10n_fr_business_document_import/__manifest__.py
  l10n_fr_das2/__manifest__.py
  l10n_fr_fec_oca/__manifest__.py
  l10n_fr_intrastat_product/__manifest__.py
  l10n_fr_intrastat_service/__manifest__.py
  l10n_fr_mis_reports/__manifest__.py
  setup/_metapackage/setup.py
Labels: approved, bot is merging ⏳

#297 [REF][12.0] Fix Travis, ignoring modules
  .travis.yml
  l10n_fr_business_document_import/__manifest__.py
  l10n_fr_chorus_account/__manifest__.py
  l10n_fr_chorus_facturx/__manifest__.py
  l10n_fr_chorus_sale/__manifest__.py
  l10n_fr_chorus_ubl/__manifest__.py
  l10n_fr_fec_oca/__manifest__.py
Labels: bot is merging ⏳

#286 [12.0] FIX CI
  requirements.txt
Labels: bot is merging ⏳

#287 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
Labels: help wanted, bot is merging ⏳

#240 [12.0] siret: FIX readonly status on company fields
  l10n_fr_siret/models/company.py
Labels: approved, bot is merging ⏳
