Repository OCA/l10n-france, pull requests merged in 2022-07, with the labels that each got.

#348 [FIX] company_registry : do not set company_registry field readonly on res.company model
  l10n_fr_siret/models/company.py
Labels: bot is merging ⏳, stale

#368 [11.0] l10n_fr_intrastat_product: Add mig script
  l10n_fr_intrastat_product/migrations/11.0.1.0.0/post-migration.py
  l10n_fr_intrastat_product/migrations/11.0.1.0.0/pre-migration.py
Labels: approved

#369 [14.0] l10n_fr_intrastat_product: add mig script
  l10n_fr_intrastat_product/migrations/14.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳
