Repository OCA/l10n-france, pull requests merged in 2022-11, with the labels that each got.

#382 [16.0][MIG] l10n_fr_hr_check_ssnid
  l10n_fr_hr_check_ssnid/README.rst
  l10n_fr_hr_check_ssnid/__init__.py
  l10n_fr_hr_check_ssnid/__manifest__.py
  l10n_fr_hr_check_ssnid/i18n/fr.po
  l10n_fr_hr_check_ssnid/i18n/l10n_fr_hr_check_ssnid.pot
  l10n_fr_hr_check_ssnid/models/__init__.py
  l10n_fr_hr_check_ssnid/models/hr_employee.py
  l10n_fr_hr_check_ssnid/readme/CONTRIBUTORS.rst
  l10n_fr_hr_check_ssnid/readme/DESCRIPTION.rst
  l10n_fr_hr_check_ssnid/readme/INSTALL.rst
  l10n_fr_hr_check_ssnid/readme/USAGE.rst
  l10n_fr_hr_check_ssnid/static/description/icon.png
  l10n_fr_hr_check_ssnid/static/description/index.html
  l10n_fr_hr_check_ssnid/tests/__init__.py
  l10n_fr_hr_check_ssnid/tests/test_ssnid.py
  l10n_fr_hr_check_ssnid/views/hr_employee.xml
  requirements.txt
  setup/l10n_fr_hr_check_ssnid/odoo/addons/l10n_fr_hr_check_ssnid
  setup/l10n_fr_hr_check_ssnid/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#386 [REF] update Copier Answers.
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
Labels: bot is merging ⏳

#385 [14.0] l10n_fr_department: excludes module partner_contact_department
  l10n_fr_department/__manifest__.py
Labels: approved, bot is merging ⏳

#388 [16.0][REF] Copier Update
  .copier-answers.yml
  .pre-commit-config.yaml
  README.md
Labels: bot is merging ⏳
