Repository OCA/l10n-france, pull requests merged in 2022-12, with the labels that each got.

#389 [14.0][IMP] l10n_fr_chorus_account: Add support for statuts "Intégré partiel"
  l10n_fr_chorus_account/models/chorus_flow.py
  l10n_fr_chorus_account/views/chorus_flow.xml
  l10n_fr_chorus_account/wizard/account_invoice_chorus_send.py
Labels: bot is merging ⏳

#339 [15.0][MIG] DES
  .pre-commit-config.yaml
  l10n_fr_account_tax_unece/data/account_tax_template.xml
  l10n_fr_account_tax_unece/post_install.py
  l10n_fr_intrastat_service/README.rst
  l10n_fr_intrastat_service/__init__.py
  l10n_fr_intrastat_service/__manifest__.py
  l10n_fr_intrastat_service/data/des.xsd
  l10n_fr_intrastat_service/data/intrastat_service_reminder.xml
  l10n_fr_intrastat_service/i18n/am.po
  l10n_fr_intrastat_service/i18n/ca.po
  l10n_fr_intrastat_service/i18n/de.po
  l10n_fr_intrastat_service/i18n/el_GR.po
  l10n_fr_intrastat_service/i18n/es.po
  l10n_fr_intrastat_service/i18n/es_ES.po
  l10n_fr_intrastat_service/i18n/fi.po
  l10n_fr_intrastat_service/i18n/fr.po
  l10n_fr_intrastat_service/i18n/gl.po
  l10n_fr_intrastat_service/i18n/it.po
  l10n_fr_intrastat_service/i18n/l10n_fr_intrastat_service.pot
  l10n_fr_intrastat_service/i18n/nb_NO.po
  l10n_fr_intrastat_service/i18n/pt.po
  l10n_fr_intrastat_service/i18n/pt_BR.po
  l10n_fr_intrastat_service/i18n/pt_PT.po
  l10n_fr_intrastat_service/i18n/sl.po
  l10n_fr_intrastat_service/i18n/tr.po
  l10n_fr_intrastat_service/models/__init__.py
  l10n_fr_intrastat_service/models/intrastat_service.py
  l10n_fr_intrastat_service/readme/CONTRIBUTORS.rst
  l10n_fr_intrastat_service/readme/DESCRIPTION.rst
  l10n_fr_intrastat_service/readme/USAGE.rst
  l10n_fr_intrastat_service/report/__init__.py
  l10n_fr_intrastat_service/report/intrastat_service_report_xls.py
  l10n_fr_intrastat_service/security/intrastat_service_security.xml
  l10n_fr_intrastat_service/security/ir.model.access.csv
  l10n_fr_intrastat_service/static/description/icon.png
  l10n_fr_intrastat_service/static/description/index.html
  l10n_fr_intrastat_service/tests/__init__.py
  l10n_fr_intrastat_service/tests/test_fr_intrastat_service.py
  l10n_fr_intrastat_service/views/intrastat_service_view.xml
  l10n_fr_siret/__manifest__.py
  l10n_fr_siret/models/res_partner.py
  requirements.txt
  setup/l10n_fr_intrastat_service/odoo/addons/l10n_fr_intrastat_service
  setup/l10n_fr_intrastat_service/setup.py
Labels: bot is merging ⏳

#341 [15.0][MIG] DEB
  l10n_fr_intrastat_product/README.rst
  l10n_fr_intrastat_product/__init__.py
  l10n_fr_intrastat_product/__manifest__.py
  l10n_fr_intrastat_product/data/account_fiscal_position_template.xml
  l10n_fr_intrastat_product/data/deb.xsd
  l10n_fr_intrastat_product/data/intrastat_product_reminder.xml
  l10n_fr_intrastat_product/data/intrastat_transaction.xml
  l10n_fr_intrastat_product/demo/intrastat_demo.xml
  l10n_fr_intrastat_product/i18n/am.po
  l10n_fr_intrastat_product/i18n/bg.po
  l10n_fr_intrastat_product/i18n/ca.po
  l10n_fr_intrastat_product/i18n/da.po
  l10n_fr_intrastat_product/i18n/de.po
  l10n_fr_intrastat_product/i18n/el_GR.po
  l10n_fr_intrastat_product/i18n/es.po
  l10n_fr_intrastat_product/i18n/es_ES.po
  l10n_fr_intrastat_product/i18n/es_MX.po
  l10n_fr_intrastat_product/i18n/fi.po
  l10n_fr_intrastat_product/i18n/fr.po
  l10n_fr_intrastat_product/i18n/fr_CH.po
  l10n_fr_intrastat_product/i18n/gl.po
  l10n_fr_intrastat_product/i18n/hr.po
  l10n_fr_intrastat_product/i18n/it.po
  l10n_fr_intrastat_product/i18n/l10n_fr_intrastat_product.pot
  l10n_fr_intrastat_product/i18n/nb_NO.po
  l10n_fr_intrastat_product/i18n/nl.po
  l10n_fr_intrastat_product/i18n/pt.po
  l10n_fr_intrastat_product/i18n/pt_BR.po
  l10n_fr_intrastat_product/i18n/pt_PT.po
  l10n_fr_intrastat_product/i18n/sl.po
  l10n_fr_intrastat_product/i18n/tr.po
  l10n_fr_intrastat_product/models/__init__.py
  l10n_fr_intrastat_product/models/intrastat_product_declaration.py
  l10n_fr_intrastat_product/models/intrastat_transaction.py
  l10n_fr_intrastat_product/models/intrastat_unit.py
  l10n_fr_intrastat_product/models/res_company.py
  l10n_fr_intrastat_product/models/res_partner.py
  l10n_fr_intrastat_product/models/stock.py
  l10n_fr_intrastat_product/post_install.py
  l10n_fr_intrastat_product/readme/CONFIGURE.rst
  l10n_fr_intrastat_product/readme/CONTRIBUTORS.rst
  l10n_fr_intrastat_product/readme/DESCRIPTION.rst
  l10n_fr_intrastat_product/readme/USAGE.rst
  l10n_fr_intrastat_product/security/intrastat_product_security.xml
  l10n_fr_intrastat_product/security/ir.model.access.csv
  l10n_fr_intrastat_product/static/description/icon.png
  l10n_fr_intrastat_product/static/description/index.html
  l10n_fr_intrastat_product/views/intrastat_product_declaration.xml
  l10n_fr_intrastat_product/views/intrastat_transaction.xml
  l10n_fr_intrastat_product/views/intrastat_unit.xml
  l10n_fr_intrastat_product/views/product_template.xml
  l10n_fr_intrastat_product/views/res_config_settings.xml
  l10n_fr_intrastat_product/views/res_partner.xml
  l10n_fr_intrastat_product/wizards/__init__.py
  l10n_fr_intrastat_product/wizards/res_config_settings.py
  setup/l10n_fr_intrastat_product/odoo/addons/l10n_fr_intrastat_product
  setup/l10n_fr_intrastat_product/setup.py
Labels: bot is merging ⏳, stale

#394 [15.0][IMP] l10n_fr_department: improve performances
  l10n_fr_department/model/res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#391 [16.0][MIG] l10n_fr_siret
  l10n_fr_siret/README.rst
  l10n_fr_siret/__init__.py
  l10n_fr_siret/__manifest__.py
  l10n_fr_siret/demo/partner_demo.xml
  l10n_fr_siret/i18n/bg.po
  l10n_fr_siret/i18n/cs_CZ.po
  l10n_fr_siret/i18n/da.po
  l10n_fr_siret/i18n/de.po
  l10n_fr_siret/i18n/el_GR.po
  l10n_fr_siret/i18n/es.po
  l10n_fr_siret/i18n/es_MX.po
  l10n_fr_siret/i18n/fi.po
  l10n_fr_siret/i18n/fr.po
  l10n_fr_siret/i18n/fr_CH.po
  l10n_fr_siret/i18n/hr.po
  l10n_fr_siret/i18n/it.po
  l10n_fr_siret/i18n/l10n_fr_siret.pot
  l10n_fr_siret/i18n/nb_NO.po
  l10n_fr_siret/i18n/nl.po
  l10n_fr_siret/i18n/pt.po
  l10n_fr_siret/i18n/pt_BR.po
  l10n_fr_siret/i18n/sl.po
  l10n_fr_siret/models/__init__.py
  l10n_fr_siret/models/res_company.py
  l10n_fr_siret/models/res_partner.py
  l10n_fr_siret/post_install.py
  l10n_fr_siret/readme/CONTRIBUTORS.rst
  l10n_fr_siret/readme/DESCRIPTION.rst
  l10n_fr_siret/readme/USAGE.rst
  l10n_fr_siret/static/description/icon.png
  l10n_fr_siret/static/description/index.html
  l10n_fr_siret/static/description/partner_duplicate_warning.png
  l10n_fr_siret/tests/__init__.py
  l10n_fr_siret/tests/test_fr_siret.py
  l10n_fr_siret/views/res_company.xml
  l10n_fr_siret/views/res_partner.xml
  requirements.txt
  setup/l10n_fr_siret/odoo/addons/l10n_fr_siret
  setup/l10n_fr_siret/setup.py
Labels: bot is merging ⏳

#398 [16.0][MIG] l10n_fr_state
  l10n_fr_state/README.rst
  l10n_fr_state/__init__.py
  l10n_fr_state/__manifest__.py
  l10n_fr_state/data/res_country_state.xml
  l10n_fr_state/i18n/fr.po
  l10n_fr_state/i18n/l10n_fr_state.pot
  l10n_fr_state/pre_init_hook.py
  l10n_fr_state/readme/CONTRIBUTORS.rst
  l10n_fr_state/readme/DESCRIPTION.rst
  l10n_fr_state/static/description/icon.png
  l10n_fr_state/static/description/index.html
  l10n_fr_state/static/src/img/screenshots/1.png
  setup/l10n_fr_state/odoo/addons/l10n_fr_state
  setup/l10n_fr_state/setup.py
Labels: bot is merging ⏳

#402 [15.0][FIX] chorus py3o (forward-port)
  l10n_fr_chorus_account/models/res_company.py
  l10n_fr_chorus_facturx/models/account_move.py
Labels: bot is merging ⏳

#400 [16.0][MIG] l10n_fr_account_tax_unece
  l10n_fr_account_tax_unece/README.rst
  l10n_fr_account_tax_unece/__init__.py
  l10n_fr_account_tax_unece/__manifest__.py
  l10n_fr_account_tax_unece/data/account_tax_template.xml
  l10n_fr_account_tax_unece/i18n/l10n_fr_account_tax_unece.pot
  l10n_fr_account_tax_unece/post_install.py
  l10n_fr_account_tax_unece/readme/CONTRIBUTORS.rst
  l10n_fr_account_tax_unece/readme/DESCRIPTION.rst
  l10n_fr_account_tax_unece/static/description/icon.png
  l10n_fr_account_tax_unece/static/description/index.html
  setup/l10n_fr_account_tax_unece/odoo/addons/l10n_fr_account_tax_unece
  setup/l10n_fr_account_tax_unece/setup.py
Labels: bot is merging ⏳

#392 [16.0][MIG] l10n_fr_siret_lookup
  l10n_fr_siret_lookup/README.rst
  l10n_fr_siret_lookup/__init__.py
  l10n_fr_siret_lookup/__manifest__.py
  l10n_fr_siret_lookup/i18n/fr.po
  l10n_fr_siret_lookup/i18n/l10n_fr_siret_lookup.pot
  l10n_fr_siret_lookup/models/__init__.py
  l10n_fr_siret_lookup/models/res_partner.py
  l10n_fr_siret_lookup/readme/CONTRIBUTORS.rst
  l10n_fr_siret_lookup/readme/CREDITS.rst
  l10n_fr_siret_lookup/readme/DESCRIPTION.rst
  l10n_fr_siret_lookup/readme/USAGE.rst
  l10n_fr_siret_lookup/security/ir.model.access.csv
  l10n_fr_siret_lookup/static/description/icon.png
  l10n_fr_siret_lookup/static/description/index.html
  l10n_fr_siret_lookup/views/res_partner.xml
  l10n_fr_siret_lookup/wizard/__init__.py
  l10n_fr_siret_lookup/wizard/fr_siret_lookup.py
  l10n_fr_siret_lookup/wizard/fr_siret_lookup_view.xml
  requirements.txt
  setup/l10n_fr_siret_lookup/odoo/addons/l10n_fr_siret_lookup
  setup/l10n_fr_siret_lookup/setup.py
Labels: bot is merging ⏳
