Repository OCA/l10n-france, pull requests merged in 2023-10, with the labels that each got.

#445 [IMP] l10n_fr_department : if country is not defined on partner, use the country of the company of the partner, to guess the department
  l10n_fr_department/model/res_partner.py
  l10n_fr_department/tests/test_department.py
Labels: bot is merging ⏳, stale

#464 [16.0] intrastat: set lang in mail template
  l10n_fr_intrastat_product/data/intrastat_product_reminder.xml
  l10n_fr_intrastat_service/data/mail_template.xml
Labels: bot is merging ⏳, no stale

#423 [16.0][MIG] l10n_fr_oca
  l10n_fr_oca/README.rst
  l10n_fr_oca/__init__.py
  l10n_fr_oca/__manifest__.py
  l10n_fr_oca/data/account.account.template.csv
  l10n_fr_oca/data/account.group.template.csv
  l10n_fr_oca/data/account_account_template_default_tax.xml
  l10n_fr_oca/data/account_chart_template_configure_data.xml
  l10n_fr_oca/data/account_chart_template_data.xml
  l10n_fr_oca/data/account_data.xml
  l10n_fr_oca/data/account_fiscal_position_template_data.xml
  l10n_fr_oca/data/account_reconcile_model_template.xml
  l10n_fr_oca/data/account_tax_data.xml
  l10n_fr_oca/data/l10n_fr_chart_data.xml
  l10n_fr_oca/demo/demo_company.xml
  l10n_fr_oca/i18n/l10n_fr_oca.pot
  l10n_fr_oca/readme/CONTRIBUTORS.rst
  l10n_fr_oca/readme/DESCRIPTION.rst
  l10n_fr_oca/static/description/icon.png
  l10n_fr_oca/static/description/index.html
  setup/l10n_fr_oca/odoo/addons/l10n_fr_oca
  setup/l10n_fr_oca/setup.py
Labels: bot is merging ⏳
