Repository OCA/l10n-france, pull requests merged in 2024-11, with the labels that each got.

#563 [16.0][FIX] l10n_fr_account_vat_return: fix journal entry generated in negative VAT scenario + many improvements
  l10n_fr_account_vat_return/__manifest__.py
  l10n_fr_account_vat_return/data/l10n.fr.account.vat.box.csv
  l10n_fr_account_vat_return/migrations/0.0.0/pre-migration.py
  l10n_fr_account_vat_return/models/account_tax.py
  l10n_fr_account_vat_return/models/l10n_fr_account_vat_return.py
  l10n_fr_account_vat_return/security/ir.model.access.csv
  l10n_fr_account_vat_return/tests/test_fr_account_vat_return.py
  l10n_fr_account_vat_return/views/l10n_fr_account_vat_return.xml
  l10n_fr_account_vat_return/wizards/__init__.py
  l10n_fr_account_vat_return/wizards/l10n_fr_vat_autoliq_manual.py
  l10n_fr_account_vat_return/wizards/l10n_fr_vat_autoliq_manual_view.xml
  l10n_fr_account_vat_return/wizards/l10n_fr_vat_draft_move_option.py
Labels: approved, ready to merge, bot is merging ⏳

#582 [16.0][FIX] l10n_fr_account_vat_return: fix pdf filename
  l10n_fr_account_vat_return/models/l10n_fr_account_vat_return.py
Labels: bot is merging ⏳

#581 [14.0] l10n_fr_account_vat_return: backport several fixes and improvements
  l10n_fr_account_vat_return/models/l10n_fr_account_vat_return.py
Labels: bot is merging ⏳

#515 [FIX] l10n_fr_siret[_lookup]: remove wrong dependency
  l10n_fr_siret/README.rst
  l10n_fr_siret/__manifest__.py
  l10n_fr_siret/readme/INSTALL.rst
  l10n_fr_siret/static/description/index.html
  l10n_fr_siret_lookup/README.rst
  l10n_fr_siret_lookup/__manifest__.py
  l10n_fr_siret_lookup/readme/INSTALL.rst
  l10n_fr_siret_lookup/static/description/index.html
  requirements.txt
Labels: bot is merging ⏳, stale
