Repository OCA/l10n-france, pull requests merged in 2025-04, with the labels that each got.

#623 [16.0] l10n_fr_account_vat_return: update for millesime 2025
  l10n_fr_account_vat_return/README.rst
  l10n_fr_account_vat_return/__init__.py
  l10n_fr_account_vat_return/__manifest__.py
  l10n_fr_account_vat_return/data/l10n.fr.account.vat.box.csv
  l10n_fr_account_vat_return/migrations/16.0.6.0.0/post-migration.py
  l10n_fr_account_vat_return/models/l10n_fr_account_vat_box.py
  l10n_fr_account_vat_return/models/l10n_fr_account_vat_return.py
  l10n_fr_account_vat_return/models/res_company.py
  l10n_fr_account_vat_return/post_install.py
  l10n_fr_account_vat_return/readme/DESCRIPTION.rst
  l10n_fr_account_vat_return/report/CA3_cerfa.pdf
  l10n_fr_account_vat_return/security/ir.model.access.csv
  l10n_fr_account_vat_return/static/description/index.html
  l10n_fr_account_vat_return/tests/test_fr_account_vat_return.py
  l10n_fr_account_vat_return/views/l10n_fr_account_vat_return.xml
  l10n_fr_account_vat_return/wizards/l10n_fr_vat_autoliq_manual.py
  l10n_fr_account_vat_return/wizards/l10n_fr_vat_autoliq_manual_view.xml
  l10n_fr_account_vat_return/wizards/res_config_settings.py
  l10n_fr_account_vat_return/wizards/res_config_settings.xml
Labels: bot is merging ⏳

#604 [IMP] l10n_fr_siret_lookup: add check for active companies
  l10n_fr_siret_lookup/README.rst
  l10n_fr_siret_lookup/i18n/es.po
  l10n_fr_siret_lookup/i18n/fr.po
  l10n_fr_siret_lookup/i18n/l10n_fr_siret_lookup.pot
  l10n_fr_siret_lookup/models/res_partner.py
  l10n_fr_siret_lookup/readme/USAGE.rst
  l10n_fr_siret_lookup/static/description/index.html
  l10n_fr_siret_lookup/wizard/fr_siret_lookup.py
  l10n_fr_siret_lookup/wizard/fr_siret_lookup_view.xml
Labels: bot is merging ⏳

#643 [16.0][FIX] l10n_fr_intrastat_product: Incompatibility with other intrastat
  l10n_fr_intrastat_product/README.rst
  l10n_fr_intrastat_product/models/intrastat_product_declaration.py
  l10n_fr_intrastat_product/readme/CONTRIBUTORS.rst
  l10n_fr_intrastat_product/static/description/index.html
  l10n_fr_intrastat_product/views/intrastat_product_declaration.xml
Labels: approved, bot is merging ⏳

#647 [17.0][FIX] l10n_fr_pos_caisse_ap_ip: remove BF tag
  l10n_fr_pos_caisse_ap_ip/models/pos_payment_method.py
Labels: bot is merging ⏳

#646 [18.0][FIX] l10n_fr_pos_caisse_ap_ip: remove BF tag
  l10n_fr_pos_caisse_ap_ip/models/pos_payment_method.py
Labels: bot is merging ⏳

#648 [14.0][FIX] l10n_fr_pos_caisse_ap_ip: remove BF tag
  l10n_fr_pos_caisse_ap_ip/models/pos_payment_method.py
Labels: bot is merging ⏳

#605 [16.0][IMP] l10n_fr_chorus_account: backport view improvements from v18
  l10n_fr_chorus_account/models/account_move.py
  l10n_fr_chorus_account/models/chorus_flow.py
  l10n_fr_chorus_account/models/res_company.py
  l10n_fr_chorus_account/security/group.xml
  l10n_fr_chorus_account/security/ir.model.access.csv
  l10n_fr_chorus_account/views/account_move.xml
  l10n_fr_chorus_account/views/chorus_flow.xml
  l10n_fr_chorus_account/views/chorus_partner_service.xml
  l10n_fr_chorus_account/views/config_settings.xml
  l10n_fr_chorus_account/views/res_partner.xml
  l10n_fr_chorus_account/wizard/account_invoice_chorus_send.py
  l10n_fr_chorus_account/wizard/account_invoice_chorus_send_view.xml
  l10n_fr_chorus_sale/models/sale_order.py
  l10n_fr_chorus_sale/views/sale_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#644 [18.0][FIX] l10n_fr_department La Réunion
  l10n_fr_department/model/res_partner.py
Labels: bot is merging ⏳

#621 [IMP] l10n_fr_department: Add department also on company model
  l10n_fr_department/model/__init__.py
  l10n_fr_department/model/res_company.py
Labels: bot is merging ⏳

#650 [15.0][FIX] l10n_fr_chorus_account: fix when a chorus flow has more than 10 invoices
  l10n_fr_chorus_account/models/chorus_flow.py
  l10n_fr_chorus_account/models/res_company.py
Labels: bot is merging ⏳

#651 [14.0][FIX] l10n_fr_chorus_account: fix when a chorus flow has more than 10 invoices
  l10n_fr_chorus_account/models/chorus_flow.py
  l10n_fr_chorus_account/models/company.py
Labels: bot is merging ⏳

#649 [17.0] Chorus: source for chorus service can be easily inherited + fix when a flow has more than 10 invoices
  l10n_fr_chorus_account/models/account_move.py
  l10n_fr_chorus_account/models/chorus_flow.py
  l10n_fr_chorus_account/models/chorus_partner_service.py
  l10n_fr_chorus_account/models/res_company.py
  l10n_fr_chorus_account/models/res_partner.py
  l10n_fr_chorus_account/security/group.xml
  l10n_fr_chorus_account/security/ir.model.access.csv
  l10n_fr_chorus_account/views/account_move.xml
  l10n_fr_chorus_account/views/chorus_flow.xml
  l10n_fr_chorus_account/views/chorus_partner_service.xml
  l10n_fr_chorus_account/views/res_partner.xml
  l10n_fr_chorus_facturx/models/account_move.py
  l10n_fr_chorus_sale/models/sale_order.py
  l10n_fr_chorus_sale/views/sale_order.xml
Labels: bot is merging ⏳
